### ISSUE TITLE
Deprecated Functionality: substr()

### ISSUE THREAD

**Issue by magecommerce** [Alekseon/AlekseonEav#40]
Exception #0 (Exception): Deprecated Functionality: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/app/code/Alekseon/AlekseonEav/Model/Attribute/DefaultValueProviderRepository.php on line 75

**Comment by marcinfr** [comment]
Thank You for letting us know. 
Its fixed.
