### ISSUE TITLE
Translate label

### ISSUE THREAD

**Issue by albertdxc** [Alekseon/AlekseonEav#44]
Good morning! We have your module installed in a Magento 2 but there are 4 classes that are missing translations, would it be possible for you to correct them so we can update the module?

1st It would be in: vendor\alekseon\custom-forms-builder\Block\Adminhtml\Form\Edit\Tab\General.php

On line 118: {'label' => 'Admin Note',} for {'label' => __('Admin Note'),}   [DONE] 

2º It would be in: vendor\alekseon\alekseon-eav\Block\Adminhtml\Entity\Grid.php

On line 104: {'header' => $attribute->getDefaultFrontendLabel(),} by {'header' => __($attribute->getDefaultFrontendLabel()),}

3º It would be in: vendor\alekseon\alekseon-eav\Block\Adminhtml\Entity\Edit\Form.php

On line 80: {'label' => $attribute->getDefaultFrontendLabel(),} by {'label' => __($attribute->getDefaultFrontendLabel()),}

4º It would be in: \vendor\alekseon\alekseon-eav\Block\Adminhtml\Attribute\Edit\Tab\FrontendLabels.php

On line 85: {'label' => $store->getName(),} by {'label' => __($store->getName()),}

**Comment by marcinfr** [comment]
Hi @albertdxc 
Thank You for Your notices.

All fixes are done in:
alekseon/custom-forms-builder version 102.3.11
alekseon/alekseon-eav version 101.2.11
