### ISSUE TITLE
More translations

### ISSUE THREAD

**Issue by albertdxc** [Alekseon/AlekseonEav#45]
Thanks for the previous translations, I have found some more, if you could add them. Thanks for everything.

1st It would be in: alekseon\custom-forms-builder\Model\FieldOptionSources.php

On line 92: {'label' => $option->getLabel(),} for {'label' => __($option->getLabel()),}

2º It would be in: alekseon\custom-forms-builder\view\adminhtml\templates\form\edit\tab\fields.phtml

On line 22: {Tab Name: <input type="text" class="label-input"></input>} by {__('Tab Name:') <input type="text" class="label-input"></input>}

3º It would be in: alekseon\widget-forms\Observer\AddFrontendInputBlockOptions.php

On line 54: {'label' => $data['label'],} by {'label' => __($data['label']),}

I may find some more, I hope I don't bother you.

**Comment by marcinfr** [comment]
Hi @albertdxc 
Translations have been added, please update packages.
